name        : "guitar-tuner"
description : "Simple guitar tuner using the Web Audio API."
baseurl     : "/guitar-tuner"

markdown : redcarpet
pygments : true

navCategories : ["Project", "Application"]
